name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
      pages: write
      
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Build using Vite
        run: npm run build

      - name: what's going on
        run: |
            ls
            cd dist
            ls
            cd ..

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
